name: App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_lint_typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: cd app && yarn --frozen-lockfile
      - name: Test
        run: cd app && yarn test
      - name: Lint
        run: cd app && yarn lint